api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: eveth-net

log:
  level: INFO
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

ping:
  entryPoint: web

metrics:
  prometheus: {}

tracing: {}

# Enable API and dashboard
api:
  dashboard: true
  insecure: true
